/*
 * GUI_Frame.java
 *
 * Created on 3 september 2008, 15:42
 */



/**
 *
 * @author  Bami
 */
public class myFrame extends javax.swing.JFrame {

    /** Creates new form GUI_Frame */
    public myFrame() {
        initComponents();
        this.setVisible(true);
    }
    public void setText(String s) {
        logTextArea.append(s);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify thiss code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        hostComboBox = new javax.swing.JComboBox();
        portLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        serverStartButton = new javax.swing.JToggleButton();
        codebaseLabel = new javax.swing.JLabel();
        codebaseTextField = new javax.swing.JTextField();
        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hostLabel.setText("Host");

        hostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "127.0.0.1", "10.0.0.2" }));
        hostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostComboBoxActionPerformed(evt);
            }
        });

        portLabel.setText("Port");

        portTextField.setText("80");

        serverStartButton.setBackground(new java.awt.Color(255, 0, 0));
        serverStartButton.setText("GESTOPT");
        serverStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverStartButtonActionPerformed(evt);
            }
        });

        codebaseLabel.setText("Codebase");

        codebaseTextField.setText("C:\\httpdocs\\");
            codebaseTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    codebaseTextFieldActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
            topPanel.setLayout(topPanelLayout);
            topPanelLayout.setHorizontalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hostLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(hostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(portLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(codebaseLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(codebaseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(serverStartButton)
                    .addContainerGap())
            );
            topPanelLayout.setVerticalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(portLabel)
                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serverStartButton)
                        .addComponent(codebaseLabel)
                        .addComponent(codebaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(19, Short.MAX_VALUE))
            );

            logScrollPane.setBackground(new java.awt.Color(255, 255, 255));
            logScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

            logTextArea.setColumns(20);
            logTextArea.setRows(5);
            logScrollPane.setViewportView(logTextArea);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void hostComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_hostComboBoxActionPerformed

private void serverStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverStartButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_serverStartButtonActionPerformed

private void codebaseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codebaseTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_codebaseTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codebaseLabel;
    private javax.swing.JTextField codebaseTextField;
    private javax.swing.JComboBox hostComboBox;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JToggleButton serverStartButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
