package server;

import java.awt.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class myFrame extends javax.swing.JFrame {
    Control parent;
    InetAddress[] all;
    /** Creates new form GUI_Frame */
    public myFrame(Control c) {
	 parent = c;
	    initComponents();
	    this.setVisible(true);
	try {
	   
	    InetAddress in = InetAddress.getLocalHost();
	    all = InetAddress.getAllByName(in.getHostName());
	    String[] allStrings = new String[all.length];
	    int i;
	    for (i=0; i<all.length; i++) {
		allStrings[i] = all[i].toString();
		}

	    hostComboBox.setModel(new javax.swing.DefaultComboBoxModel(allStrings));
	} catch (UnknownHostException ex) {
	    Logger.getLogger(myFrame.class.getName()).log(Level.SEVERE, null, ex);
	}
    }
    
    public InetAddress getCurrentlySelectedAdapter() {
	return all[hostComboBox.getSelectedIndex()];
    }
    public String getCodePath() {
	return codebaseTextField.getText();
    }
    
    public void setText(String s) {
        logTextArea.append(s);
	logScrollPane.getVerticalScrollBar().setValue(logScrollPane.getVerticalScrollBar().getMaximum());

    }
    public int getPort() {
        return Integer.parseInt(portTextField.getText());
    }
    
    public void setButtonText(String s, Color c) {
        serverStartButton.setText(s);
        serverStartButton.setBackground(c);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify thiss code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        hostComboBox = new javax.swing.JComboBox();
        portLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        codebaseLabel = new javax.swing.JLabel();
        codebaseTextField = new javax.swing.JTextField();
        serverStartButton = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hostLabel.setText("Host");

        hostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "127.0.0.1" }));
        hostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostComboBoxActionPerformed(evt);
            }
        });

        portLabel.setText("Port");

        portTextField.setText("80");

        codebaseLabel.setText("Codebase");

        codebaseTextField.setText("C:\\httpdocs\\");
            codebaseTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    codebaseTextFieldActionPerformed(evt);
                }
            });

            serverStartButton.setText("SERVER");
            serverStartButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    serverStartButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
            topPanel.setLayout(topPanelLayout);
            topPanelLayout.setHorizontalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hostLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(hostComboBox, 0, 204, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(portLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(codebaseLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(codebaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(serverStartButton)
                    .addContainerGap())
            );
            topPanelLayout.setVerticalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serverStartButton)
                        .addComponent(codebaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codebaseLabel)
                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(portLabel)
                        .addComponent(hostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            logTextArea.setColumns(20);
            logTextArea.setEditable(false);
            logTextArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
            logTextArea.setRows(5);
            logScrollPane.setViewportView(logTextArea);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                    .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(logScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void hostComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_hostComboBoxActionPerformed

private void codebaseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codebaseTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_codebaseTextFieldActionPerformed

private void serverStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverStartButtonActionPerformed
parent.doButton();
}//GEN-LAST:event_serverStartButtonActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codebaseLabel;
    private javax.swing.JTextField codebaseTextField;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JComboBox hostComboBox;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton serverStartButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
